import os 
import pandas as pd 
csv_file=os.path.join("Datasets","housing","housing.csv")
df = pd.read_csv(csv_file)

#excel_file=os.path.join("Datasets","housing","housing.xlsx")
#data = pd.read_excel(excel_file)

print("\nLOADING CSV AND READING CSV FILE \n")
print("\nABOUT head()\n")
print(df.head())
print("\nABOUT tail() \n")
print(df.tail())
print("\nABOUT Describe()\n")
print(df.describe())
print("\nABOUT info() \n")
print(df.info())
print("\nABOUT shape() \n")
print(df.shape[0],"\n\n")
print(df.shape[1])
print("\nABOUT value_counts \n")
print(df['ocean_proximity'].value_counts())
print("\nABOUT LIST() \n")
print(df.columns.tolist())
print("do the same for the excel file ")

excel_file=os.path.join("Datasets","housing","housing.xlsx")
data = pd.read_excel(excel_file)

print("\nLOADING Excel AND READING Excel FILE \n")
print("\nABOUT head()\n")
print(data.head())
print("\nABOUT tail() \n")
print(data.tail())
print("\nABOUT Desciibe()\n")
print(data.describe())
print("\nABOUT info() \n")
print(data.info())
print("\nABOUT shape() \n")
print(data.shape[0],"\n\n")
print(data.shape[1])
print("\nABOUT value_counts \n")
print(data['ocean_proximity'].value_counts())
print("\nABOUT LIST() \n")
print(data.columns.tolist())
print("do the same for the excel file ")